apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXTAUTH_URL: "http://frontend:3000"
  NEXT_PUBLIC_API_URL: "http://backend:8000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "mysql+aiomysql://root:rootpassword@mysql:3306/productivity"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  JWT_SECRET: ""
